import { ChunkManager } from '../../src/information-theory/steganography/chunk-manager.js';
import { PasswordVault } from '../../src/structures/vault/immutable-vault.js';
import { describe, it, expect } from '../utils/test-runner.js';

describe('Secure ID Generation (Sentinel PBT)', () => {
    it('Property: ChunkManager.generateId must use secure crypto, not Math.random()', async () => {
        // Stub Math.random to always return a predictable value (e.g., 0.5)
        const originalRandom = Math.random;
        Math.random = () => 0.5;

        try {
            const id1 = ChunkManager.generateId();
            const id2 = ChunkManager.generateId();

            // Should be a valid UUID string
            expect(typeof id1).toBe('string');
            expect(id1.length).toBeGreaterThan(10);

            // Should be different, showing Math.random is NOT being used (which would result in identical outputs)
            // Or if they are valid UUIDs generated by crypto, they'll naturally differ
            expect(id1 !== id2).toBe(true);

            // Standard check if Math.random() was generating an ID it would be 'xxxxxxx...' based on the stub
            // The old implementation with Math.random() = 0.5 would return '88888888-8888-4888-8888-888888888888'
            expect(id1 !== '88888888-8888-4888-8888-888888888888').toBe(true);
        } finally {
            // Restore Math.random
            Math.random = originalRandom;
        }
    });

    it('Property: PasswordVault.generateId must use secure crypto, not Math.random()', async () => {
        // Stub Math.random to always return a predictable value
        const originalRandom = Math.random;
        Math.random = () => 0.5;

        try {
            const id1 = PasswordVault.generateId();
            const id2 = PasswordVault.generateId();

            // Should be a valid UUID string
            expect(typeof id1).toBe('string');
            expect(id1.length).toBeGreaterThan(10);

            // Note: Date.now() might make them slightly different in old implementation,
            // but the random part would be constant "i"
            // With Math.random()=0.5, toString(36).substring(2, 11) is "i"
            expect(id1.endsWith('-i')).toBe(false);

            expect(id1 !== id2).toBe(true);
        } finally {
            // Restore Math.random
            Math.random = originalRandom;
        }
    });
});
